%DNA script

%Rice alpha amylase original not optimised
DNAseq1 = 'ATGAAGCTGTCTACCATTCTGTTTACCGCTTGTGCTACTCTGGCTCTCGCTCTGGCTCAGGTTCTGTTTCAGGGTTTCAACTGGGAGTCTTGGAAGGAGAACGGCGGATGGTACAACTTCCTGATGGGAAAGGTCGACGATATCGCCGCTGCCGGTATTACCCACGTCTGGCTGCCCCCTCCCTCTCATTCCGTTGGCGAGCAGGGATACATGCCTGGACGACTGTACGACCTCGATGCCTCGAAGTACGGTAACGAGGCTCAGCTGAAGTCTCTCATTGAGGCCTTCCACGGCAAGGGCGTGCAGGTCATCGCCGACATCGTGATTAACCACCGAACCGCTGAGCATAAGGATGGACGAGGTATCTACTGTCTGTTTGAGGGTGGCACTCCTGACTCCCGACTCGATTGGGGTCCCCACATGATCTGCCGAGACGATCCTTACGGCGACGGAACCGGTAACCCTGACACTGGAGCTGATTTCGCTGCCGCTCCCGACATTGATCATCTGAACAAGCGAGTCCAGCGAGAGCTCATTGGTTGGCTGGACTGGCTCAAGATGGACATCGGCTTCGATGCCTGGCGACTGGACTTTGCTAAGGGATACTCCGCCGACATGGCTAAGATCTACATTGATGCCACCGAGCCTTCGTTTGCCGTTGCTGAGATCTGGACTTCTATGGCCAACGGAGGTGACGGAAAGCCCAACTACGATCAGAACGCTCACCGACAGGAGCTGGTCAACTGGGTTGACCGAGTGGGCGGAGCCAACTCGAACGGCACCGCTTTCGACTTTACCACTAAGGGTATTCTCAACGTGGCTGTGGAGGGAGAGCTGTGGCGACTCCGAGGTGAGGACGGCAAGGCTCCTGGAATGATCGGTTGGTGGCCCGCCAAGGCTACCACTTTCGTTGACAACCACGATACCGGCTCCACTCAGCATCTGTGGCCTTTTCCCTCGGACAAGGTCATGCAGGGCTACGCCTACATTCTCACCCACCCTGGAAACCCCTGTATCTTCTACGACCATTTCTTTGATTGGGGCCTGAAGGAAGAGATCGAGCGACTCGTCTCTATTCGAAACCGACAGGGAATCCACCCTGCTTCTGAGCTGCGAATTATGGAGGCCGACTCCGATCTGTACCTCGCTGAGATCGACGGCAAGGTCATCACTAAGATTGGACCCCGATACGACGTCGAGCATCTGATTCCCGAGGGATTTCAGGTGGTGGCTCACGGAGACGGTTACGCTATTTGGGAGAAGATTTGA';

DNAseq2 = 'ATGAAGCTCTCCACCATCCTTTTTACAGCTTGTGCAACGCTCGCACTTGCCCTTGCTCAGGTTCTGTTCCAAGGTTTTAACTGGGAGTCCTGGAAAGAAAACGGAGGTTGGTATAACTTTCTTATGGGCAAAGTCGACGATATTGCAGCTGCAGGTATCACCCACGTCTGGCTTCCTCCCCCTTCTCATTCGGTTGGAGAGCAAGGATACATGCCCGGTCGACTCTATGATCTGGATGCTTCCAAATATGGTAACGAGGCTCAACTGAAGTCTCTCATCGAGGCATTTCATGGAAAAGGTGTTCAGGTCATTGCAGACATTGTCATTAACCACCGTACCGCAGAGCACAAAGATGGCCGGGGCATTTATTGCCTGTTTGAAGGTGGTACGCCCGACTCTCGACTTGACTGGGGCCCTCATATGATTTGCCGTGATGACCCTTATGGAGATGGAACAGGTAACCCCGACACAGGAGCTGACTTTGCCGCTGCACCCGACATTGATCACCTGAATAAACGAGTGCAGCGGGAACTTATCGGATGGCTCGATTGGCTGAAAATGGATATCGGATTCGATGCTTGGAGACTGGATTTCGCAAAAGGTTATTCTGCAGATATGGCTAAAATCTACATCGATGCTACAGAACCCTCGTTTGCTGTGGCTGAAATTTGGACATCCATGGCTAACGGCGGAGACGGAAAACCCAATTATGATCAGAACGCCCATCGTCAAGAGCTCGTCAATTGGGTCGATCGAGTGGGTGGTGCAAATTCTAACGGTACAGCATTTGACTTTACCACCAAAGGTATTCTGAATGTGGCCGTCGAAGGAGAGCTTTGGCGTCTCCGGGGAGAGGATGGAAAAGCCCCCGGAATGATTGGTTGGTGGCCTGCAAAGGCCACTACTTTCGTCGATAATCATGACACCGGATCCACACAGCATCTTTGGCCCTTTCCTAGCGACAAGGTGATGCAAGGATATGCCTACATCCTTACCCATCCTGGAAACCCTTGTATCTTTTACGACCACTTCTTCGACTGGGGACTTAAAGAAGAAATCGAGCGTCTTGTTTCCATCCGAAATAGACAAGGAATCCATCCTGCATCCGAGCTGCGTATTATGGAAGCAGACTCCGACCTTTACCTGGCTGAAATCGATGGCAAAGTTATTACAAAAATTGGCCCTCGGTATGATGTGGAGCACCTCATTCCCGAGGGCTTCCAGGTTGTCGCACATGGAGACGGTTATGCCATCTGGGAGAAAATCTGA';

opti2 = 'ATGAAACTCTCCACAATTCTTTTCACAGCATGCGCAACCCTCGCCCTCGCTCTTGCACAGGTCCTCTTTCAGGGTTTCAATTGGGAGTCGTGGAAAGAGAACGGCGGTTGGTACAATTTTCTTATGGGAAAAGTTGACGATATCGCCGCCGCAGGTATTACTCATGTTTGGCTCCCTCCTCCTAGCCATAGCGTTGGTGAACAAGGCTATATGCCTGGCCGACTCTATGATCTTGACGCCTCCAAATATGGCAATGAAGCTCAACTCAAGTCCCTCATCGAGGCTTTTCATGGAAAAGGCGTCCAAGTTATCGCAGACATCGTTATCAACCACAGAACCGCTGAGCACAAGGATGGCCGAGGAATCTACTGCCTTTTCGAGGGAGGTACTCCTGATTCCCGTCTTGACTGGGGTCCCCACATGATTTGTAGAGATGATCCCTATGGAGACGGAACGGGTAATCCCGACACAGGAGCAGATTTCGCTGCTGCTCCCGATATCGACCATCTGAACAAACGGGTTCAACGAGAACTTATCGGATGGCTGGATTGGCTCAAGATGGACATTGGATTTGACGCATGGCGTCTTGACTTCGCCAAGGGTTACTCCGCAGACATGGCCAAAATCTACATTGATGCAACAGAGCCCTCGTTCGCCGTCGCTGAGATCTGGACTTCCATGGCAAACGGCGGAGACGGAAAACCTAACTACGACCAAAACGCACATCGACAAGAGCTGGTGAATTGGGTTGACCGAGTTGGCGGCGCCAATTCTAATGGAACTGCCTTTGACTTCACCACGAAAGGCATTCTTAACGTGGCCGTCGAAGGCGAACTCTGGCGTCTTCGGGGCGAAGATGGTAAAGCACCCGGTATGATTGGATGGTGGCCCGCCAAGGCCACCACTTTTGTGGATAATCATGATACGGGCTCTACGCAACACCTGTGGCCTTTTCCCTCTGACAAGGTCATGCAGGGCTATGCTTATATTCTCACGCATCCCGGCAACCCCTGCATCTTCTACGATCATTTCTTTGACTGGGGTCTTAAAGAAGAAATTGAACGGCTGGTCAGCATCCGGAATCGACAGGGTATTCACCCCGCCTCCGAACTCCGGATCATGGAGGCTGACAGCGACCTGTACCTCGCTGAAATTGACGGCAAAGTTATCACCAAGATTGGTCCTCGATATGACGTTGAACACCTCATCCCCGAGGGCTTCCAGGTTGTCGCACACGGAGATGGCTACGCTATTTGGGAAAAGATTTGA';
%% count number of codon discrepancies
NTDiscrepancyCount = 0;
for i = 1:length(DNAseq1)
    if opti2(i) ~= DNAseq2(i)
        NTDiscrepancyCount = NTDiscrepancyCount + 1;
    end
end

CodonDiscrepancyCount = 0;
codonLength = length(DNAseq2)/3;
codoncounter = 1;
number_of_differences = zeros(1,codonLength);
for i = 1:3:length(DNAseq1)
    for j = 0:2
        if DNAseq2(i+j) ~= DNAseq1 (i+j)
            number_of_differences(codoncounter) = number_of_differences(codoncounter) + 1;
            if number_of_differences(codoncounter) == 1
                CodonDiscrepancyCount = CodonDiscrepancyCount + 1;
            end
        end
    end
    codoncounter = codoncounter +1;
end

ceros = find(number_of_differences == 0);
unos = find(number_of_differences == 1);
dos = find(number_of_differences == 2);
tres = find(number_of_differences == 3);

number_of_zeros = length(ceros);
number_of_ones = length(unos);
number_of_twos = length(dos);
number_of_threes = length(tres);
 bar([0,1,2,3],[number_of_zeros,number_of_ones,number_of_twos,number_of_threes])
figure
explode = [1 1 0 1];
% labels = {['Unchanged codons',num2str(number_of_zeros/codoncounter)],['Changed codons by 1nt change',num2str(number_of_zeros/codoncounter)],['Changed codons by 3nt changes',num2str(number_of_zeros/codoncounter)]};

p= pie([number_of_zeros,number_of_ones,number_of_twos,number_of_threes],explode);%,labels);



%% do aminoacid profile


cb = codonbias(DNAseq1,'PIE',true);
cb2 = codonbias(DNAseq2,'PIE',true);
cb3 = codonbias(opti2,'PIE',true);

%% 
figure
codonmap1 = codoncount(DNAseq1,'Figure', true);
figure
codonmap2 = codoncount(DNAseq2,'Figure', true);


%%
elements = fields(codonmap1);
for i = 1:numel(elements)
  codonmap1.(elements{i}) = codonmap1.(elements{i})/codonLength;
  codonmap2.(elements{i}) = codonmap2.(elements{i})/codonLength;
end

%%
row = 1;
for l = 1:8:64
    for m = 0:7
   codonmap1restructured.codon{row,1+m} = elements{l+m};
   codonmap1restructured.value(row,1+m) = codonmap1.(elements{l+m});
    end
    row = row+1;
end

heatmap(codonmap1restructured.value)

row = 1;
for l = 1:8:64
    for m = 0:7
   codonmap2restructured.codon{row,1+m} = elements{l+m};
   codonmap2restructured.value(row,1+m) = codonmap2.(elements{l+m});
    end
    row = row+1;
end
figure
heatmap(codonmap2restructured.value)



